name: Generate PDF

# NOTE: due to this on: push: filepath , workflow is only triggered if there's any change in latex file
# To trigger on every push, regardless of whether latex was changed or not, keep just on: push
on:
  push:
    paths:
      - 'software_engineer.tex'

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: blang/latex:latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Compile LaTeX document
      run: |
        pdflatex software_engineer.tex

    - name: Upload PDF
      uses: actions/upload-artifact@v4
      with:
        name: software_engineer.pdf
        path: software_engineer.pdf
